# Generated by Django 3.2.8 on 2021-11-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radamtaa', '0002_auto_20211102_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtaa',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
